tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "neovim"
brew "gh"
brew "git"
brew "starship"
brew "rustup"
brew "fnm"
brew "pnpm"
brew "python"
brew "ripgrep"
brew "fd"
brew "rust-analyzer"

cask "rectangle"
cask "discord"
cask "slack"
cask "spotify"
cask "bitwarden"
cask "github"
cask "brave-browser"
cask "warp"
cask "font-fira-code-nerd-font"
